description: 'Documentation RAG'

prompts:
  - id: file://./test/prompts.mjs:documentation_rag
    label: documentation-rag

providers:
  - id: anthropic:messages:claude-3-5-sonnet-20240620
    config:
      temperature: 0
  # - id: openai:gpt-4o
  #   config:
  #     temperature: 0

defaultTest:
  options:
    provider: anthropic:messages:claude-3-5-sonnet-20240620

assertionTemplates:
  containsTestAPIs:
    type: icontains-all
    value:
      - 'Test APIs'
      - '`cloudflare:test` module definition'

tests:
  - description: Hello World worker
    vars:
      test_file: file://./test/vars/hello.spec.ts
    assert:
      - $ref: "#/assertionTemplates/containsTestAPIs"

  - description: Embeddings worker
    vars:
      test_file: file://./test/vars/embeddings.spec.ts
    assert:
      - $ref: "#/assertionTemplates/containsTestAPIs"

      - type: icontains-all
        value:
          - 'Workers AI'
          - 'env.AI.run()'
          - 'embedding'

  - description: Similarity Search worker
    vars:
      test_file: file://./test/vars/similarity.spec.ts
    assert:
      - type: icontains-all
        value:
          - 'embedding'
          - 'Vectorize'
