#:schema node_modules/wrangler/config-schema.json
name = "wall-e"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "Text", globs = ["**/*.md"], fallthrough = true }
]

[vars]
GH_APP_ID = "902658"
