name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - src/**
      - test/**
      - wiki/**
      - package.json
      - yarn.lock
      - vitest.config.ts
      - wrangler.*

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run unit tests
        run: yarn test
