name: Update README

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - scripts/**

jobs:
  update-readme:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Update README
        run: npm run update:readme

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain README.md)" ]; then
            git add README.md
            git commit -m "chore: update README"
            git push
          else
            echo "No changes to README.md. Skipping commit."
          fi
